import java.util.*; //importing all the classes from java's util library.. Because it has Scanner class which is used to take input from user
import java.lang.*; //importing all the classes from java's lang library.. Because it has Math class which is used to generate random numbers

class Guesser { // Guesser class is used to generate random numbers and also to take input from user to choose the level of the game
    double guessNum; // guessNum is used to store the random number generated by the system
    int num; // num is used to store the random number generated by the system after typecasting double to int

    public int guessNumber() { // guessNumber method is used to generate random numbers
        System.out.println("==============================================================");
        System.out.println("Please choose your level:- Easy(E), Medium(M), Hard(H)");
        System.out.println("==============================================================");
        Scanner scan = new Scanner(System.in);
        guessNum = Math.random(); // Math.random() method is used to generate random numbers
        String choice = scan.next(); // scan.next() method is used to take input from user
        char ch = choice.charAt(0); // charAt(0) method is used to take the first character from the string
        switch (ch)
        {
            case 'E': guessNum = guessNum * 10; // guessNum is multiplied by 10 to get a number between 0 to 10
                break;

            case 'M': guessNum = guessNum * 100; // guessNum is multiplied by 100 to get a number between 0 to 100
                break;

            case 'H': guessNum = guessNum * 1000; // guessNum is multiplied by 1000 to get a number between 0 to 1000
                break;

            default: System.out.println("==============================================================");
                System.out.println("Please either enter choice in Uppercase or re-enter your choice! ");
                System.out.println("==============================================================");
                System.exit(0); // System.exit(0) is used to exit the program
                break; 
        }
        System.out.println("==============================================================");
        System.out.println("System is choosing a number for you :) ");
        System.out.println("==============================================================");
        num = (int) guessNum; // typecasting double to int
        return num; // returning the number to the main method
    }
}

class Player { // Player class is used to take input from user to guess the number
    int pguessNum; // pguessNum is used to store the number guessed by the player

    public int guessNumber() { // guessNumber method is used to take input from user to guess the number generated by the system and return the number to the main method to compare
        Scanner scan = new Scanner(System.in); // Scanner class is used to take input from user
        System.out.println("==============================================================");
        System.out.println("Kindly guess the number");
        System.out.println("==============================================================");
        pguessNum = scan.nextInt(); // scan.nextInt() method is used to take input from user
        return pguessNum; // returning the number to the main method
    }
}

class Umpire { // Umpire class is used to compare the number guessed by the player and the number generated by the system

    int numFromGuesser; // numFromGuesser is used to store the number generated by the system
    int numFromPlayer1; // numFromPlayer1 is used to store the number guessed by the player1
    int numFromPlayer2; // numFromPlayer2 is used to store the number guessed by the player2
    int numFromPlayer3; // numFromPlayer3 is used to store the number guessed by the player3


    public void collectNumFromGuesser() { // collectNumFromGuesser method is used to collect the number generated by the system
        Guesser g = new Guesser(); // creating an object of Guesser class
        numFromGuesser = g.guessNumber(); 
    }


    public void collectNumFromPlayer() { // collectNumFromPlayer method is used to collect the number guessed by the player
        Player p1 = new Player(); // creating an object of Player class
        Player p2 = new Player(); 
        Player p3 = new Player(); 


        numFromPlayer1 = p1.guessNumber(); 
        numFromPlayer2 = p2.guessNumber(); 
        numFromPlayer3 = p3.guessNumber();
    }

    void compare() { // compare method is used to compare the number guessed by the player and the number generated by the system

        if (numFromGuesser == numFromPlayer1) { // if the number guessed by the player is equal to the number generated by the system then the player wins the game
            if (numFromGuesser == numFromPlayer2 && numFromGuesser == numFromPlayer3) { // if all the players guess the number correctly then all the players win the game
                System.out.println("Game tied all three players guessed correctly and won");
                System.out.println("::::::::::: Thank you for playing, have a great one ahead :)  :::::::::::::");
            } else if (numFromGuesser == numFromPlayer2) { // if player1 and player2 guess the number correctly then player1 and player2 win the game
                System.out.println("Player 1 and Player2 won the game, player 3 lost");
                System.out.println("::::::::::: Thank you for playing, have a great one ahead :)  :::::::::::::");
            } else if (numFromGuesser == numFromPlayer3) { // if player1 and player3 guess the number correctly then player1 and player3 win the game
                System.out.println("Player 1 and Player3 won and player 2 lost ");
                System.out.println("::::::::::: Thank you for playing, have a great one ahead :)  :::::::::::::");
            } else { // if only player1 guess the number correctly then player1 wins the game

                System.out.println("Player 1 won the game and everyone else lost");
                System.out.println("::::::::::: Thank you for playing, have a great one ahead :)  :::::::::::::");
            }
        } else if (numFromGuesser == numFromPlayer2) { // if the number guessed by the player is equal to the number generated by the system then the player wins the game

            if (numFromGuesser == numFromPlayer3) { // if player2 and player3 guess the number correctly then player2 and player3 win the game
                System.out.println("Player 2 and Player3 won the game and player 1 lost");
                System.out.println("::::::::::: Thank you for playing, have a great one ahead :)  :::::::::::::");
            } else { // if only player2 guess the number correctly then player2 wins the game
                System.out.println("Player 2 won the game and other lost");
                System.out.println("::::::::::: Thank you for playing, have a great one ahead :)  :::::::::::::");
            }
        } else if (numFromGuesser == numFromPlayer3) { // if the number guessed by the player is equal to the number generated by the system then the player wins the game
            System.out.println("Player 3 won the game and everyone else lost ");
            System.out.println("::::::::::: Thank you for playing, have a great one ahead :)  :::::::::::::");
        } else { // if no one guesses the number correctly then no one wins the game
            System.out.println("No one guessed correctly! The number which was to be guessed is:- " + numFromGuesser);
            System.out.println("::::::::::: Thank you for playing, have a great one ahead :)  :::::::::::::");
        }
    }

}


public class Launchgame { // Launchgame class is used to launch the game

    public static void main(String[] args) { // main method is used to call the methods of other classes
        Umpire u = new Umpire();
        u.collectNumFromGuesser();
        u.collectNumFromPlayer();
        u.compare();
    }
}